name: meru_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  bloc_test: ^9.1.5
  mocktail: ^1.0.3
  test: ^1.24.9
  flutter_launcher_icons: "^0.14.4"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
